---
title: "Response-to-reviewers_R1"
output: pdf_document
date: "2023-10-18"
---

Thank you for for the time and care taken by the editorial team and reviewers in providing feedback to this manuscript. No doubt, the revised version submitted is more articulate than the first. We've provided extensive feedback to all comments from each reviewer in \textcolor{blue}{blue} and directly quoted the revised portion of the manuscript as relevant in \textcolor{blue}{\emph{italicized blue}} 

## Reviewer #1: 

The article extends the concept of spatial accessibility and applies it to a fairness analysis of different modes of transportation. The article uses travel data from a week in Madrid as an example to analyze spatial accessibility in the city. However, the article has the following issues:

1. Lack of Innovation: The article's improvement on spatial accessibility mainly involves incorporating the ratio of travel frequencies as weight in travel costs. This improvement is relatively minor and the method used does not demonstrate superiority over traditional accessibility approaches.

\textcolor{blue}{Thank you for this comment but we disagree with this characterization of the our manuscript. 

The spatial availability measure we extend for multi-modal application does not use _"the ratio of travel frequencies as weight in travel costs"_. In our empirical example, we use mode-segmented origin-destination data to estimate travel impedance based on trip lengths. The travel impedance can be understood as "travel costs". In this way, the travel frequencies are reflected as a weight in the calculation of travel impedance itself as well as reflected in the population factor and job opportunities variable. So your comment inaccurately characterizes our method. Spatial availability consists of a total balancing factor (based on travel impedance and population) that proportionally allocates opportunities. In this manuscript, we demonstrate how the mode-specific travel impedance and populations can be used to calculate _competitive_ accessibility, by mode (considering competition by all modes based on the travel impedance) and _constrained_ to add up to the total sum of opportunities available in the region. In this way, each spatial availability value is a proportion of the total sum of opportunities in the region.

Particularly, in the "Discussion and conclusions" section, the advantages that spatial availability offers when considering the competitive accessibility to opportunities by different modes. In a way, the ratio of travel frequencies are incorporated, but the result is a proportional allocation of opportunities, based on their competitive travel-cost-advantage and relative-mode-using-population, back to each spatial unit. Ultimately, the sum of all spatial availability values for each mode sum up to the total in the region. This is not true for _any_ other type of accessibility measure. It is also not plainly obvious that this can be done using spatial availability for multiple modes; thus this paper fills this gap.

Further, we believe we do demonstrate superiority of our measure throughout the manuscript. For example,we summarize in the Discussion and Conclusions: _"With spatial availability, the number of opportunities that are captured (of the total opportunities in the region) by each mode can be individually calculated. From there, the difference between how many spatially available opportunities one mode captures versus another can be investigated. This is the advantage of the spatial availability measure, particularly its multimodal extension."_. Ultimately, the spatial availability values are a product of proportional allocation: each value is a proportion of the total opportunities in the region. Put in another way, the total opportunities in the region are _finite_, and this is how spatial availability is introduced against un/constrained and non/competitive accessibility measures. The conceptualization of opportunities as _finite_ within the spatial availability measures gives spatial availability values inherent meaning that is not available for any other type of accessibility measure. This meaning allows us to explore, for instance, the difference in spatial availability values between modes (i.e., job opportunities that are spatially available based on the travel-impedance and populations of all modes) and the spatial availability per capita benchmarks as done in the empirical examples. 

However, we agree we could make this more advantage of spatial availability more explicitly clear in all sections, as such the "Introduction", "A review of multimodal accessibility measures", and "Discussion and Conclusions" section have been expanded and/or clarified.

Introduction:
_The question of how much one mode-using population can access at the expense of another mode-using population is a pertinent equity question in the evaluation of policy scenarios, especially those that impact modes differently. For instance, consider the impact of a low emission zone (LEZ). A LEZ is a policy of spatial and modal discrimination: the circulation of vehicles that are excessively polluting are restricted in specific regions. Depending on the level of vehicle restriction, LEZ have been shown to significantly improve air quality [@holmanReviewEfficacyLow2015] and air-quality related health outcomes[@margaryanLowEmissionZones2021]. From the perspective of accessibility to opportunities, LEZ explicitly lower the access that restricted-vehicle using populations have to opportunities within the LEZ. However, if conceptualizing opportunities in a region as finite, one populations' lose is another populations' gain. The populations using non-restricted modes (e.g., walking, cycling, transit, and less-polluting vehicles) to travel into LEZ will have more access than before the LEZ implementation._

_This evaluation is especially urgent as LEZ are in effect in cities globally; their reception [@tarrinoortizPublicAcceptabilityLow2021] and impact on certain activity types such as shopping [@tarrinoortizImpactLowEmission2023] have been mixed. They may also be having negative impacts on disadvantaged populations who have become mobility-restricted [@devrijNooneVisitsMe2022; @verbeekJustManagementUrban2022; @liottaWhatDrivesInequalities2023]. Measures that evaluate the accessibility of modes given both constrained and competitive considerations are lacking in the literature, but are needed, to evaluate such an intervention's impact on accessibility gains and losses within a finite conceptualization._

A review of multimodal accessibility measures:
- extended the explanation of Hasen-type measure and the consideration of competition in accessibility (shen-type measure) with additional examples from the literature. See the revised sections.

Discussion and Conclusions:
XXXXXXXXXXX

}

2. Insufficient Experimental Data: The article uses questionnaire data from a week in Madrid, but lacks basic descriptions of the questionnaire data. Additionally, the daily travel data of approximately 30,000 trips is significantly limited, and there is no description of the criteria for selecting the dates. The typicality of the experimental data is questionable.

\textcolor{blue}{Thank you for this comment. To clarify, the empirical data used is a travel survey conducted by the City of Mardid. This is a conventional travel survey that is conducted in cities around the world. This experimental data is the best and most complete travel survey conducted in Madrid to date. I'm unsure where you got the 30,000 trip number from but I presume you are citing the maximum 'opportunity' or 'population' number in Figure 2 or 3? The more intense the colour, the higher the value it represents. The most intensely coloured TAZ have ~30,000 jobs while the least intensely coloured have ~1,000 or fewer (figure 2). The total number of jobs in the City are 847,574, this is also the sum of the total spatial availability in the City. 

Furthermore, results from accessibility data isn't typically generalization anyways, it is highly context-specific. The purpose of using the experimental data is do demonstrate what we can presume to be true about LEZ. Specifically: that LEZ restrict car mobility hence you would expect to see higher accessibility for non-car modes. This is intuition, and through spatial availability this can be seen, specifically in using the intuition behind the multimodal extension of this method (which is the proportional allocation of opportunities based on population competition and modal competition) 

We have updated the manuscript to improve clarity for the readers:

Introduction:
_In Section 3, the spatial availability of four mode categories is calculated for the city of Madrid, Spain after the 2017 LEZ is implemented. Using mode-specific home-to-work origin-destination 2018 travel survey as empirical data, we demonstrate inequities of spatial availability within and outside the LEZ for each sub-population using car, transit, cycling and walking modes._

Multimodal data and methods:
_The 2018 Community of Madrid travel survey [@comunidaddemadridResultadosEDM20182020] is the source of data for this empirical example: it is a representative survey that reflects a snap-shot of the travel patterns for a typical day of the working week in 2018. Specifically, it includes 222,744 trips taken from a representative sample of 85,064 households across the traffic analysis zones (TAZ) representing the Community of Madrid (population of 6,507,184 over 3 years old) through population elevation factors._

_In this empirical example, we only use a sub-set of the survey, specifically home-to-work trips, by all modes, to demonstrate multimodal spatial availability of employment opportunities. The total population who travels to work from an origin (i.e., the worker), and the destinations (i.e., the employment opportunity), for the City of Madrid (a sub-set of the Community of Madrid) is visualized in Figure \ref{fig:Fig2} and Figure \ref{fig:Fig3}. Both figures are displayed at the level of TAZ (the $i$ and $j$ zones) that correspond to the survey._...

Captions to Figure 2 and Figure 3:
- Jobs $O_j$ taken by people living and working in Madrid as reported by the home-to-work flows in the 2018 travel survey.
- Figure 3: Population living and working in Madrid by four summarized modal categories $P^m_i$ as reported by the home-to-work flows in the 2018 travel survey.
}

3. Lack of Data-Driven Analysis: In the analysis section, a large amount of data is used to analyze people's travel behavior in different areas. The analysis of spatial accessibility only considers the differences in the modes of travel mentioned earlier. The analysis results are somewhat one-sided, and examining the indicator from multiple perspectives would provide a more objective view. It is recommended to expand the dimensions of the analysis.

\textcolor{blue}{Thanks for this comment. We believe with the additional detail added to the manuscript to address your and other reviewers' comments, overall clarity has been improved. 

In this work, we outline issues associated with accessibility measures stemming from the lack of competition considerations and being constrained: namely, neglecting competition can be an oversight when opportunities have a capacity, and neglecting to constraint the global measures makes interpretation in comparisons difficult. We elaborate on these issues in a synthetic example of a synthetic region with two populations, one using a faster mode and one using a slower mode to access opportunities.

Having demonstrated the merits in how multimodal spatial availability considers competition and can be more easily interpreted as it is constrained (each value is a score that is a proportion of the total opportunities in the region), we then expand on an empirical example. The multimodal spatial availability of employment opportunities in Madrid, a city that has recently put in place a LEZ. We demonstrate how the measure can be used to understand differences in spatial availability between modes, and how the restriction on one mode could improve the spatial availability for others. The empirical case is used as a snapshot of the estimated spatial availability as informed by the origin-destination flows from the 2018 travel survey. It is a proof-of-concept on empirical data that spatially visuals what singly-constrained competitive accessibility to employment, by mode, looks like.

As we believe your comment is referring to the dimensionality of the empirical example, we added the following sentences to the beginning of the Results section to demonstrate this intention clearly:
_As it is worth re-iterating, the empirical example reflects a snap-shot of the calculated multimodal spatial availability using data from the 2018 travel survey. It is intended to visualize the spatial trends in availability of employment opportunities, by mode, and demonstrate how spatial availability can be interpreted to discuss the competitive advantage of lower travel impedance modes within Madrid Centro._}

4. Disorganized Format: The article's methodology section contains numerous formulas and variables, but the definitions of these variables are unclear and difficult to read. There are also numerous formatting errors, and Table 1 is disorganized and unappealing. It is recommended to revise these issues.

\textcolor{blue}{Thank you for this comment, but we are not sure how to address all of these items. We have used the PLOS ONE template. All definitions of variables are included and variables are correctly included in mathematical notation in the original manuscript. As you did not provide us with specific line or page numbers indicating were errors may be, we took a careful read through of the manuscript, particularly focusing on the methodology, and attempted to streamline where we could.

We also made sure Table 1 starts on a new page, when it runs across pages the formatting resulted in some disorganization.}

## Reviewer #2: 

This paper has sound mathematical foundations and allows to answer its research question in an elegant way (how to measure competition for e.g. jobs based on spatial accessibility?). I also really appreciated the fact that the paper was very didactic. Still, I have concerns about the relevance of the paper for future research.

More specifically, the new measure proposed by the authors has clear limitations:
i) it focuses on the competition for jobs and is not useful for studying access to non-competitive or semi-competitive resources such as amenities.

\textcolor{blue}{Thank you for this comment; Indeed, we have grappled with this idea for some time. At this point, we are convinced that _all_ opportunities have some sort of capacity. For instance, green spaces are often considered non-competitive, however, some standards are provided in the form of unit of green space per capita (e.g., [Natural England](https://redfrogforum.org/wp-content/uploads/2019/11/67-Nature-Nearby%E2%80%99-Accessible-Natural-Greenspace-Guidance.pdf) set an Accessible Natural Greenspace Standard recommending that everyone have at a minimum: a minimum of one ha of statutory Local Nature Reserves per thousand population). This is some amount of green space per person, that no one else is using at the same time. Though Local Nature Reserves have large capacities - they still have a capacity - and thus spatial availability can be used to measure competitive (and constrained) access to this sort of opportunity. As planning literature moves more towards the creation of standards, these standards can be used to directly inform results from spatial availability analysis. However, this idea is not discussed in the manuscript itself.

<!--should I discuss this in the conclusion? Perhaps yes, alongside other standards. otherwise not sure what to change in the manuscript to address this comment. -->
Additionally, even if this idea of all opportunities having a capacity is not conceptually discussed in the paper, this method is still relevant for many opportunity types. Historically, competitive opportunities have been extensively studied in accessibility literature. For instance, health-care and employment opportunities in the long tradition of competitive accessibility studies, e.g., [@taoInvestigatingImpactsPublic2020a; @maoMeasuringSpatialAccessibility2013; @shenLocationCharacteristicsInnercity1998]. These opportunities are also more readily available in historically point-of-interest datasets and reported on in long-form censuses. Further, places of employment have been seen as proxies for _all_ types of activities (as they correspond to some sort of employment opportunity as activities typically are a service), see work by @hellingChangingIntrametropolitanAccessibility1998.}

ii) it doesn't allow to study absolute gains or losses in accessibility from public transportation infrastructure improvements or changes.

\textcolor{blue}{Great point - spatial availability can certainly be used to capture absolute gains and losses. In fact, logically, the gains and losses produced by using a competitive and constrained measure allows for a clear interpretation.

Unfortunately however, we do not quantify any before- or after- scenarios in this work. We only have access to a travel survey from after the LEZ implementation in Madrid for the time being. Furthermore, the empirical example is meant as a proof-of-concept of the multimodal spatial availability extension. 

We intend to use spatial availability in the scenario analysis of before- and after- LEZ implementation from a modal and socio-economic equity perspective. We've added this intuition and limitation to the conclusion:
_In future work, we intend to use multimodal spatial availability to characterise the equity of modal accessibility losses and gains in varying LEZ policy scenario implementations._}

iii) the authors do not allow for modal shifts: they assume that the transport mode choice of households is fixed and cannot evolve due to e.g. transport infrastructure changes.

\textcolor{blue}{
Excellent point. We have thought about this potential consideration. Spatial availability is certainly compatible with some sort of modal split model. It is a flexible framework that can take in different travel impedance curves as well as proportions of populations using those travel impedance (i.e., modal splits changing). However, that demonstrate is out of scope in this paper. 

The focus of this paper is on the methodological expansion of spatial availability to quantify multiple modal options and characterise their potential competitive advantage for opportunities. The empirical example is a demonstrate of this multimodal spatial availability extension. We've made it more clear in the conclusion that this is our intention for future work. We've also improved the Introduction and Abstraction to make it more clear that this is a methodolgically focused paper with an empirical case study as snap-shot demonstration of conditions in 2018 after the LEZ implementation.}

These points limit the relevance of the new accessibility measure. The authors should, at least, specify these limitations early in the paper. The introduction should start by stating the precise research question the new accessibility measure is seeking to answer as well as its limitations). They should also justify, based on the literature, that competition for jobs is a key determinant of job market outcomes, and that there is strong inertia in mode choices.

\textcolor{blue}{ 
<!--Honestly not too sure about this one.. the point about competition in job markets is sort of tangent to this research. And mode choice inertia isn't too relevant either _because_ we are expressing this as a 'snap shot' of conditions in 2018 based on how people _behave_.--> }

Finally, the writing of the paper, and particularly of the abstract and introduction, should be improved. The abstract could state the broader relevance of the topic and summarize the results of the case study on LEZs. The introduction should start more directly by introducing the research question and its relevance and describing the new measure and its limitations.

\textcolor{blue}{ Thank you for your thoughtful comments. We have streamlined the Introduction based on your comments and other reviewers. We've also updated the Abstract. 

Regarding the limitations of the method, the limitations are in the details - specifically the travel impedance selected and the data used. The method itself is a framework. So we've augmented the Methodology and Results sections to more clearly express the assumptions embedded in the empirical example that limit it's interpretation. 
<!--Not too confident in this response... I feel like I should change more of the manuscript but not sure how as the comments aren't entirely relevant. I did not update the Abstract or Introduction too drastically. I like the flow and I think they accurately reflect what this paper does.-->}

Minor comments:
i) what are the summary statistics p10 (car: 36 min, transit: 55 min,...)? I assume they correspond to the mean.
\textcolor{blue}{
Updated! Apologies, car: '36 min' corresponds to a mean of 36 minutes and then within the brackets additional descriptive statistics (minumum value, maximum value, etc.). }
ii) I also have identified a few formatting issues (e.g. Fcij p10 and 4.72km2 p 8).
\textcolor{blue}{
Fixed! Thank you. }

## Reviewer #3: 

This manuscript extended the authors’ previous work spatial availability measure, which is a type of location-based accessibility measure that is both constrained and competitive compared to Hansen-type measure and Shen-type accessibility measure, into a multimodal framework. The new measure, multimodal spatial availability, strengthened the constrained (or finite) nature of opportunities, and the competitive nature among multimodal accessibility resulting from this constraint through a synthetic example and an empirical example of the LEZ in the city of Madrid. In conclusion, the authors demonstrated one restriction had impacted the spatial availability of opportunities for other modes using and proposed potential future uses in policy planning scenarios.
In general, the manuscript was logical and well-structured. The research problem was well defined. The data were available and quite supported the conclusion. The statistical analysis performed appropriately.

However, there are some issues:

Major issues:
Please demonstrate whether “car/motor & transit” and “bike & walk” are comparable or whether they are in an actual competitive relationship? For example, if I work 3km from where I live, maybe I will never choose to take a transit, I will always walk or ride. But if I work 20km from where I live, walking or riding to work seems impossible for me, I have to drive or take public transportation. Car/motor and transit can be in competitive relationship and people can choose which one they prefer, but not choose between motor and walk. This issue will also have an impact on the results of the research.

\textcolor{blue}{ 

Great comment. Whenever a destination can be reached by more than one mode, users of those mode are in competition for the same opportunities. 

We have improve the discussion of impedance function to make this more clear. The impedance functions for all four modes are not the same. They describe the travel behaviour of home-to-work trips (as informed by the 2018 travel surve). If you work 20 km from where you live, and its not possible to walk, you are not competing for jobs at that location with people who walk where you leave (because people don't walk). But you are competing with people who can walk (live at other closer destinations) to those jobs. 

Futhermore, average travel times for car/motor and transit are longer than bike and walk. All people don't have access to all options - completely true. But the travel impedances reflect this real travel at an aggregate based on all the trips for a mode. And on average, it is assumed that people at each origin that take a mode to a destination are in direct competition for opportunities (as opportunities are finite) -- and a part of the competition is defined by the mode-specific impedance function (the second part is the population balancing factor). This assumption, that all populations, no matter their mode, are competing for the same finite set of opportunity, is part of spatial availability. We've made this more clear in the text.

Multimodal data and methods:

_Notably, plots in Figure \ref{fig:Fig4} can be observed across modes if curious to know what trips are more likely to occur using what mode depending on trip length (as informed by the observed 2018 survey). Trips >5 minutes do not occur frequently for any mode, as such trips with short trip lengths are assigned a lower travel impedance_ $f^m(c_{ij}^m)$ _value. One reason that >5 minute trips do not frequently occur as a result of land-use (residential and job mismatch): not everyone lives in immediate proximity to their workplace. In terms of the non-motorized modes, shorter trips occurred more frequently overall for walking populations, particularly around 15 minute lengths, so a trip of approximately 15 minutes is assigned the highest_ $f^m(c_{ij}^m)$. _For biking populations, longer travel times are more common so though the highest_ $f^m(c_{ij}^m)$ _value also corresponds to approximately 15 minutes, the curve is more spread out and values decrease less rapidly at longer travel times than for the walk mode curve. A similar trend can be observed for the motorized modal options where transit mode is more spread out than car/motor mode. All in all, these observations demonstrate that, based on a given mode and travel time, a trip is more or less likely to occur and is accordingly represented in the cost of travel balancing factor_ $F_{ij}^m$ _for_ $V_i^m$.
}

Minor issues:
1. As for Fig 2 and Fig 3, please indicate the meaning of the gray color blocks in illustration.
\textcolor{blue}{
Fixed for all Figures, thank you. }
2. Please change the color scheme of fig 2. The red color scheme makes the LEZ centro area boundary, which is also in red, not visible.
\textcolor{blue}{
WILL FIX THANK YOU <!-- and I must change the labels on the legends to be ranges -->}