---
title: "Response-to-reviewers_R1"
output: pdf_document
date: "2023-10-18"
---

Thank you for for the time and care taken by the editorial team and reviewers in providing feedback to this manuscript. No doubt, the revised version submitted is more articulate than the first. Our responses to all comments from each reviewer are shown below in \textcolor{blue}{blue} and directly quoted the revised portion of the manuscript as relevant} 

## Reviewer #1: 

The article extends the concept of spatial accessibility and applies it to a fairness analysis of different modes of transportation. The article uses travel data from a week in Madrid as an example to analyze spatial accessibility in the city. However, the article has the following issues:

\textcolor{blue}{We appreciate your effort reading our submission and respond in detail to your comments below.}

1. Lack of Innovation: The article's improvement on spatial accessibility mainly involves incorporating the ratio of travel frequencies as weight in travel costs. This improvement is relatively minor and the method used does not demonstrate superiority over traditional accessibility approaches.

\textcolor{blue}{Thank you for this comment. First we would like to bring to your attention the editorial philosophy of PLoS ONE, according to which editors "make decisions on submissions based on scientific rigor, regardless of novelty," (see https://journals.plos.org/plosone/s/editorial-and-peer-review-process). Nonetheless we wish to respond to this comment.}

\textcolor{blue}{In this paper we extend our earlier work on [spatial availability](https://doi.org/10.1371/journal.pone.0278468) for the simultaneous analysis of multiple modes of transportation. You appear to be under the misaprehension that the main difference with accessibility measures is to incorporate "the ratio of travel frequencies as weight in travel costs". This is statement is not correct. The main difference is a proportional allocation mechanism that we introduced for spatial availability, and that is extended in this paper to allocate opportunities based on the proportion of travelers by different modes. This is not the same as "weighting the travel cost". In fact, each mode is modelled using its own impedance function, as shown in our empirical example, where we use origin-destination data by mode to estimate travel impedance functions specific to each mode.} 

\textcolor{blue}{While this enhancement may appear minor to you, it is not plainly obvious how spatial availability applies to multiple modes, which is why we think this paper is needed. We do not dispute that this is an incremental step in the development of a more general method, but it is a step that considerably expands the range of potential applications. Further, we contend that the method has been rigorously developed and demonstrated using an open, transparent, and reproducible example.}

\textcolor{blue}{In response to this comment we have edited the "Discussion and conclusions" section to more clearly describe the advantages that multimodal spatial availability offers when considering the accessibility to opportunities by different modes. In particular, proportional allocation of opportunities using mode-specific impedance functions means that the travel-cost-advantage of each mode can be analyzed. Further, this mechanism ensures that the sum of all spatial availability values for all modes sum up to the total number of opportunities in the region, which is not true for any other type of accessibility measure.}

\textcolor{blue}{With respect to the "superiority" of the method, a reader of our earlier paper would already be aware of what limitations of accessibility analysis spatial availability aims to address. In this paper we also try to demonstrate throughout the manuscript what our measure does that others can't. For example, in the Discussion and Conclusions we state that: "With spatial availability, the number of opportunities that are captured (of the total opportunities in the region) by each mode can be individually calculated. From there, the difference between how many spatially available opportunities one mode captures versus another can be investigated. This is the advantage of the spatial availability measure, particularly its multimodal extension.". Since the spatial availability values result from proportional allocation, each value is a proportion of the total opportunities. Put another way, we can compare the proportion of opportunities available to users of each mode, to users at each zone, to users of each mode by zone, and so on, and the values relate directly to the total opportunities in the region. This also allows us to calculate values per capita that serve as benchmark values, as shown in the empirical example.}

\textcolor{blue}{In the revised version of the paper, the advantages of spatial availability are stated more explicitly, including in the "Introduction", "A review of multimodal accessibility measures", and "Discussion and Conclusions".}

\textcolor{blue}{Introduction:}

\textcolor{blue}{The question of how much one mode-using population can access at the expense of another mode-using population is a pertinent equity question in the evaluation of policy scenarios, especially those that impact modes differently. For instance, consider the impact of a low emission zone (LEZ). A LEZ is a policy of spatial and modal discrimination: the circulation of vehicles that are excessively polluting are restricted in specific regions. Depending on the level of vehicle restriction, LEZ have been shown to significantly improve air quality [@holmanReviewEfficacyLow2015] and air-quality related health outcomes[@margaryanLowEmissionZones2021]. From the perspective of accessibility to opportunities, LEZ explicitly lower the access that restricted-vehicle using populations have to opportunities within the LEZ. However, if conceptualizing opportunities in a region as finite, one populations' lose is another populations' gain. The populations using non-restricted modes (e.g., walking, cycling, transit, and less-polluting vehicles) to travel into LEZ will have more access than before the LEZ implementation.}

\textcolor{blue}{This evaluation is especially urgent as LEZ are in effect in cities globally; their reception [@tarrinoortizPublicAcceptabilityLow2021] and impact on certain activity types such as shopping [@tarrinoortizImpactLowEmission2023] have been mixed. They may also be having negative impacts on disadvantaged populations who have become mobility-restricted [@devrijNooneVisitsMe2022; @verbeekJustManagementUrban2022; @liottaWhatDrivesInequalities2023]. Measures that evaluate the accessibility of modes given both constrained and competitive considerations are lacking in the literature, but are needed, to evaluate such an intervention's impact on accessibility gains and losses within a finite conceptualization.}

\textcolor{blue}{A review of multimodal accessibility measures:}

\textcolor{blue}{- extended the explanation of Hasen-type measure and the consideration of competition in accessibility (shen-type measure) with additional examples from the literature. See the revised sections.}

\textcolor{blue}{Discussion and Conclusions:}

\textcolor{blue}{XXXXXXXXXXX}

2. Insufficient Experimental Data: The article uses questionnaire data from a week in Madrid, but lacks basic descriptions of the questionnaire data. Additionally, the daily travel data of approximately 30,000 trips is significantly limited, and there is no description of the criteria for selecting the dates. The typicality of the experimental data is questionable.

\textcolor{blue}{Thank you for this comment. To clarify, the data are not experimental. They are observational, since they were collected using a travel survey conducted by the City of Madrid. Travel surveys are a standard instrument in transportation planning and research, and are conducted in cities around the world. The data we work with represent the most recent and most complete travel survey conducted for the region to date. We are not completely sure where you got the figure of "30,000 trips" (which you consider significantly limited); presumably you are citing the maximum 'opportunity' or 'population' numbers in Figure 2 or 3. The most intensely coloured TAZ have ~30,000 jobs while the least intensely coloured have ~1,000 or fewer (figure 2). In fact, there are 847,574 jobs in the city, which is also the sum of the total spatial availability in our analysis, as well as the number of potential trips to work.}

\textcolor{blue}{The "typicallity" of a travel survey is information about travel on a typical day, usually during a period of maximum demand (i.e., not during the summer vacation). This is standard practice for these surveys.}

\textcolor{blue}{We have updated the manuscript to provide further information about the survey for the benefit of readers:}

\textcolor{blue}{Introduction:}

\textcolor{blue}{In Section 3, the spatial availability of four mode categories is calculated for the city of Madrid, Spain after the 2017 LEZ is implemented. Using mode-specific home-to-work origin-destination 2018 travel survey as empirical data, we demonstrate inequities of spatial availability within and outside the LEZ for each sub-population using car, transit, cycling and walking modes.}

\textcolor{blue}{Multimodal data and methods:}

\textcolor{blue}{The 2018 Community of Madrid travel survey [@comunidaddemadridResultadosEDM20182020] is the source of data for this empirical example: it is a representative survey that reflects a snap-shot of the travel patterns for a typical day of the working week in 2018. Specifically, it includes 222,744 trips taken from a representative sample of 85,064 households across the traffic analysis zones (TAZ) representing the Community of Madrid (population of 6,507,184 over 3 years old) through population elevation factors.}

\textcolor{blue}{In this empirical example, we only use a sub-set of the survey, specifically home-to-work trips, by all modes, to demonstrate multimodal spatial availability of employment opportunities. The total population who travels to work from an origin (i.e., the worker), and the destinations (i.e., the employment opportunity), for the City of Madrid (a sub-set of the Community of Madrid) is visualized in Figure \ref{fig:Fig2} and Figure \ref{fig:Fig3}. Both figures are displayed at the level of TAZ (the $i$ and $j$ zones) that correspond to the survey....}

\textcolor{blue}{Captions to Figure 2 and Figure 3:}

\textcolor{blue}{- Jobs $O_j$ taken by people living and working in Madrid as reported by the home-to-work flows in the 2018 travel survey.}
\textcolor{blue}{- Figure 3: Population living and working in Madrid by four summarized modal categories $P^m_i$ as reported by the home-to-work flows in the 2018 travel survey.
}

3. Lack of Data-Driven Analysis: In the analysis section, a large amount of data is used to analyze people's travel behavior in different areas. The analysis of spatial accessibility only considers the differences in the modes of travel mentioned earlier. The analysis results are somewhat one-sided, and examining the indicator from multiple perspectives would provide a more objective view. It is recommended to expand the dimensions of the analysis.

\textcolor{blue}{Thanks for this comment.} 

\textcolor{blue}{It is somewhat puzzling that "30,000 trips" would be significantly limited (as per your comment \#2), and at the same time be "a large amount of data". We find that this comment in particular is not actionable due to its vagueness. There are no meaningful responses to "somewhat one-sided" when "somewhat" and "one-sided" do not quantify or refer to a particular side. We used all modes available in the survey, and examined the results from the perspective of each mode. What other perspectives do you suggest? What dimensions should be explored?}

\textcolor{blue}{Nevertheless, with the additional detail added to the manuscript to address your and other reviewers' comments, we believe that overall clarity has been improved.}

4. Disorganized Format: The article's methodology section contains numerous formulas and variables, but the definitions of these variables are unclear and difficult to read. There are also numerous formatting errors, and Table 1 is disorganized and unappealing. It is recommended to revise these issues.

\textcolor{blue}{Reviewer #2 identified some specific formatting issues and we fixed them. Otherwise we proofread the paper and hopefully did not leave a typo behind. We also made sure Table 1 starts on a new page, when it runs across pages the formatting resulted in some disorganization.}

\textcolor{blue}{Thank you again for your efforts trying to review our submission.}

## Reviewer #2: 

This paper has sound mathematical foundations and allows to answer its research question in an elegant way (how to measure competition for e.g. jobs based on spatial accessibility?). I also really appreciated the fact that the paper was very didactic. Still, I have concerns about the relevance of the paper for future research.

\textcolor{blue}{Thank you for your thoughtful review of our paper. Your comments were helpful to improve the clarity of the research.}

More specifically, the new measure proposed by the authors has clear limitations:
i) it focuses on the competition for jobs and is not useful for studying access to non-competitive or semi-competitive resources such as amenities.

\textcolor{blue}{Thank you for this comment. We would begin by noting that there are many types of opportunities that are clearly mutually exclusive due to competition. For this paper we focused on jobs, but there are many others, such as beds at hospitals, doctors at clinics, seats at schools, and so on. Thus, even if the measure was applicable only to opportunities subject to competition, there are numerous applications to it.}

\textcolor{blue}{That said, we have grappled for some time with the idea that some opportunities might not be subject to competition. Our current thinking, after much consideration, is that in practice every type of opportunity is subject to congestion or capacity constraint. For instance, green spaces are often considered non-competitive, however, standards for the provision of such amenties are provided in the form of units of amenity per capita. For example, Natural England recommends an Accessible Natural Greenspace Standard such that the minimum supply of space is one ha of statutory Local Nature Reserves per thousand population}^[see  https://redfrogforum.org/wp-content/uploads/2019/11/67-Nature-Nearby%E2%80%99-Accessible-Natural-Greenspace-Guidance.pdf] \textcolor{blue}{. Similarly, the World Health Organization (cited in OECD, 2013) recommends that cities provide a minimum of 9 m2 of green area per inhabitant.}^[see https://doi.org/10.1787/9789264191808-en] \textcolor{blue}{For our purposes, standards of this type translate into "how much of this resource can we give to each individual that is not allocated to anyone else?". For this reason, although Local Nature Reserves have large capacities - they still have a capacity - and thus spatial availability can be used to measure constrained accessibility to this sort of opportunity. As standards are emphasized in the planning literature, in particular for fairness in transportation (see Martens and Golub, 2021), spatial availability analysis can be used to assess standards. We believe that as other researchers discover this new measure, other applications will be found.}

ii) it doesn't allow to study absolute gains or losses in accessibility from public transportation infrastructure improvements or changes.

\textcolor{blue}{Great point. Spatial availability can certainly be used to capture absolute gains and losses. In fact, logically, the gains and losses produced by using a competitive and constrained measure allows for a clear interpretation. This would require the analyst to estimate the accessibility before and after some change to the land use or transportation system. In this paper our empirical application is a single scenario to serve as proof of concept, but in future research we intend to use spatial availability to analyze changes in the size of Madrid's Low Emissions Zone implementation from a modal and socio-economic equity perspective.}

iii) the authors do not allow for modal shifts: they assume that the transport mode choice of households is fixed and cannot evolve due to e.g. transport infrastructure changes.

\textcolor{blue}{This is an excellent point. Although spatial availability is not a model of modal split, it is certainly amenable to changes in the use of various modes. This could be implemented as follows: the results of a modal split model are used to estimate new modal shares, which in turn are used to recalculate spatial availability. The results then can be compared to the baseline scenario. In other words, the framework for spatial availability is sufficiently flexible to take in not only mode-specific travel impedance functions, but also the proportions of the populations using each mode.}

These points limit the relevance of the new accessibility measure. The authors should, at least, specify these limitations early in the paper. The introduction should start by stating the precise research question the new accessibility measure is seeking to answer as well as its limitations). They should also justify, based on the literature, that competition for jobs is a key determinant of job market outcomes, and that there is strong inertia in mode choices.

\textcolor{blue}{Your comments have been very helpful to improve the clarity of the paper, as well as the scope of what we do now, and directions for future research.}
 
Finally, the writing of the paper, and particularly of the abstract and introduction, should be improved. The abstract could state the broader relevance of the topic and summarize the results of the case study on LEZs. The introduction should start more directly by introducing the research question and its relevance and describing the new measure and its limitations.

\textcolor{blue}{We have done this. Thank you again for your thoughtful comments and suggestions to improve the paper.} 

Minor comments:

i) what are the summary statistics p10 (car: 36 min, transit: 55 min,...)? I assume they correspond to the mean.

\textcolor{blue}{Updated! Apologies, car: '36 min' corresponds to a mean of 36 minutes and then within the brackets additional descriptive statistics (minumum value, maximum value, etc.). }

ii) I also have identified a few formatting issues (e.g. Fcij p10 and 4.72km2 p 8).

\textcolor{blue}{Fixed! Thank you.}

## Reviewer #3: 

This manuscript extended the authors’ previous work spatial availability measure, which is a type of location-based accessibility measure that is both constrained and competitive compared to Hansen-type measure and Shen-type accessibility measure, into a multimodal framework. The new measure, multimodal spatial availability, strengthened the constrained (or finite) nature of opportunities, and the competitive nature among multimodal accessibility resulting from this constraint through a synthetic example and an empirical example of the LEZ in the city of Madrid. In conclusion, the authors demonstrated one restriction had impacted the spatial availability of opportunities for other modes using and proposed potential future uses in policy planning scenarios.

In general, the manuscript was logical and well-structured. The research problem was well defined. The data were available and quite supported the conclusion. The statistical analysis performed appropriately.

However, there are some issues:

Major issues:

Please demonstrate whether “car/motor & transit” and “bike & walk” are comparable or whether they are in an actual competitive relationship? For example, if I work 3km from where I live, maybe I will never choose to take a transit, I will always walk or ride. But if I work 20km from where I live, walking or riding to work seems impossible for me, I have to drive or take public transportation. Car/motor and transit can be in competitive relationship and people can choose which one they prefer, but not choose between motor and walk. This issue will also have an impact on the results of the research.

\textcolor{blue}{Great comment. The short answer is that whenever a destination can be reached by more than one mode, users of those modes are in competition for the opportunities there.} 

\textcolor{blue}{In the paper we have tried to improve the discussion to make this point more clear. The impedance functions for all four modes are not the same. They describe the travel behaviour of commuters as informed by the 2018 travel survey. To follow your example, someone who cannot walk to work because their job is 20 km from where they live, will not compete for that job against people from their same origin who do walk. However, it the place where their work is can be reached by walking by anyone from any other origin (someone who lives closer to that one destination), they would compete for the same opportunity.}

\textcolor{blue}{Futhermore, average travel times for car/motor and transit are longer than bike and walk. All people don't have access to all options - completely true. But the travel impedances reflect this real travel at an aggregate based on all the trips for a mode. And on average, it is assumed that people at each origin that take a mode to a destination are in direct competition for opportunities (as opportunities are finite) -- and a part of the competition is defined by the mode-specific impedance function (the second part is the population balancing factor). This assumption, that all populations, no matter their mode, are competing for the same finite set of opportunity, is part of spatial availability. We've made this more clear in the text.}

\textcolor{blue}{Multimodal data and methods:}

\textcolor{blue}{Notably, plots in Figure \ref{fig:Fig4} can be observed across modes if curious to know what trips are more likely to occur using what mode depending on trip length (as informed by the observed 2018 survey). Trips >5 minutes do not occur frequently for any mode, as such trips with short trip lengths are assigned a lower travel impedance $f^m(c_{ij}^m)$ value. One reason that >5 minute trips do not frequently occur as a result of land-use (residential and job mismatch): not everyone lives in immediate proximity to their workplace. In terms of the non-motorized modes, shorter trips occurred more frequently overall for walking populations, particularly around 15 minute lengths, so a trip of approximately 15 minutes is assigned the highest $f^m(c_{ij}^m)$. For biking populations, longer travel times are more common so though the highest $f^m(c_{ij}^m)$ value also corresponds to approximately 15 minutes, the curve is more spread out and values decrease less rapidly at longer travel times than for the walk mode curve. A similar trend can be observed for the motorized modal options where transit mode is more spread out than car/motor mode. All in all, these observations demonstrate that, based on a given mode and travel time, a trip is more or less likely to occur and is accordingly represented in the cost of travel balancing factor $F_{ij}^m$ for $V_i^m$.}

Minor issues:

1. As for Fig 2 and Fig 3, please indicate the meaning of the gray color blocks in illustration.

\textcolor{blue}{Fixed for all Figures, thank you.}

2. Please change the color scheme of fig 2. The red color scheme makes the LEZ centro area boundary, which is also in red, not visible.

\textcolor{blue}{WILL FIX THANK YOU}

 <!-- and I must change the labels on the legends to be ranges -->
